/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-02-17 08:46:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.modalclasses.SrcDestDate;
import java.util.ArrayList;
import java.sql.ResultSet;
import com.modalclasses.AvailableModal;

public final class busdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.modalclasses.AvailableModal");
    _jspx_imports_classes.add("com.modalclasses.SrcDestDate");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
 ArrayList<AvailableModal> ams =(ArrayList<AvailableModal>)request.getAttribute("AvailableModals"); 
      out.write('\r');
      out.write('\n');
 ArrayList<SrcDestDate> all=(ArrayList<SrcDestDate>) request.getAttribute("separate"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <!-- Style CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style.css\" />\r\n");
      out.write("    <!-- Demo CSS (No need to include it into your project) -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/demo.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/seats.css\" />\r\n");
      out.write("    \r\n");
      out.write("    <!-- bootstrP scc link -->\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("      integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <!-- botsrtarp js link -->\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("      integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"\r\n");
      out.write("      integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("      integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"main\" >\r\n");
      out.write("      <main class=\"app\">\r\n");
      out.write("        <div class=\"screen-wrap\">\r\n");
      out.write("          <section class=\"screen-bus\" style=\"opacity: 1\">\r\n");
      out.write("           ");
 for(SrcDestDate sdd :all){ 
      out.write("\r\n");
      out.write("            <div class=\"screen-bus__location-filter-wrap\">\r\n");
      out.write("              <div class=\"screen-bus__location-filter-row\">\r\n");
      out.write("                <div class=\"screen-bus__location\">\r\n");
      out.write("                  <div class=\"screen-bus__location-row\">\r\n");
      out.write("                    <span class=\"screen-bus__location-col\" style=\"font-size: 30px;font-weight: 600;\">");
      out.print(sdd.getSource());
      out.write("</span>\r\n");
      out.write("                    <span class=\"screen-home__rs-arrow\"></span>\r\n");
      out.write("                    <span class=\"screen-bus__location-col\" style=\"font-size: 30px;font-weight: 600;\">");
      out.print(sdd.getDestination());
      out.write("</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"screen-bus__date-row\">\r\n");
      out.write("                    <span>");
      out.print(sdd.getRegNo());
      out.write("</span> -\r\n");
      out.write("                    \r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"screen-bus__filter\">\r\n");
      out.write("                  <figure>\r\n");
      out.write("                    <img src=\"https://i.ibb.co/ZJt9tkM/filter.png\" />\r\n");
      out.write("                  </figure>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 }
      out.write(" \r\n");
      out.write("           \r\n");
      out.write("            ");
 for(AvailableModal av :ams){ 
      out.write("\r\n");
      out.write("            <div class=\"screen-bus__travels-wrap\">\r\n");
      out.write("              <div class=\"screen-bus__travels-row\">\r\n");
      out.write("                <div\r\n");
      out.write("                  class=\"screen-bus__travels-col\"\r\n");
      out.write("                  style=\"opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0)\"\r\n");
      out.write("                >\r\n");
      out.write("                  <div class=\"screen-bus__name-time-seat\">\r\n");
      out.write("                    <div class=\"screen-bus__name-wrap bus-name-style\">\r\n");
      out.write("                      <span class=\"screen-bus__name\" style=\"font-size: 20px;font-weight:600;\">");
      out.print(av.getRegNo() );
      out.write("</span>\r\n");
      out.write("                      <span class=\"screen-bus__type\" style=\"font-size: 20px;font-weight:600;\">Non A/C</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"screen-bus__time-wrap\">\r\n");
      out.write("                      <div class=\"screen-bus__time\">\r\n");
      out.write("                        <div class=\"screen-bus__start\" style=\"font-size: 20px;font-weight:600;\">");
      out.print(av.getArrivalTime() );
      out.write("</div>\r\n");
      out.write("                        <div class=\"screen-bus__time-arrow-wrap\">\r\n");
      out.write("                          <span class=\"screen-bus__time-arrow\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"screen-bus__end\" style=\"font-size: 20px;font-weight:600;\">");
      out.print(av.getDeparturetime() );
      out.write("</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <!-- <div class=\"screen-bus__hrs\">\r\n");
      out.write("                        <span style=\"font-size: 20px;font-weight:600;\">2 hrs</span>\r\n");
      out.write("                      </div> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"screen-bus__seat-wrap\">\r\n");
      out.write("                      <div>\r\n");
      out.write("                        <span style=\"font-weight: 500;font-size: 20px;font-weight:600;\">Seats Available: </span>\r\n");
      out.write("                        <span class=\"screen-bus__count\" style=\"font-size: 20px;\">26</span>\r\n");
      out.write("                        <!-- <span><span>â¹</span> 1220</span> -->\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"screen-bus__rating-price\">\r\n");
      out.write("                    <div class=\"screen-bus__rating-price-row\" style=\"justify-content: space-between;\">\r\n");
      out.write("    \r\n");
      out.write("                      <span><span style=\"font-weight: 500;\"> Ticket Price: </span><span>â¹</span> ");
      out.print(av.getTicketCharges() );
      out.write("</span>\r\n");
      out.write("                      <div class=\"screen-bus__price\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("                          click to book\r\n");
      out.write("                        </button>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 }
      out.write("\r\n");
      out.write("          </section>\r\n");
      out.write("        </div>\r\n");
      out.write("      </main>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\" style=\"margin-left: 485px; margin-top: 100px;\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\" style=\"width: 89%;\" >\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Choose Your Seats</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <form action=\"linklogiin\" method =\"post\">\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"bus seat2-2 border-0 p-0\">\r\n");
      out.write("          <div class=\"seat-row-1\">\r\n");
      out.write("            <ol class=\"seats\">\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-1\"\r\n");
      out.write("                  value=\"1\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-1\"> 1 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-2\"\r\n");
      out.write("                  value=\"2\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-2\"> 2 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-3\"\r\n");
      out.write("                  value=\"3\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-3\"> 3 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-4\"\r\n");
      out.write("                  value=\"4\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-4\"> 4 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"seat-row-2\">\r\n");
      out.write("            <ol class=\"seats\">\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-5\"\r\n");
      out.write("                  value=\"5\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-5\"> 5 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-6\"\r\n");
      out.write("                  value=\"6\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-6\"> 6 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-7\"\r\n");
      out.write("                  value=\"7\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-7\"> 7 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-8\"\r\n");
      out.write("                  value=\"8\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-8\"> 8 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"seat-row-3\">\r\n");
      out.write("            <ol class=\"seats\">\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-9\"\r\n");
      out.write("                  value=\"9\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-9\"> 9 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-10\"\r\n");
      out.write("                  value=\"10\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-10\"> 10 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-11\"\r\n");
      out.write("                  value=\"11\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-11\"> 11 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-12\"\r\n");
      out.write("                  value=\"12\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-12\"> 12 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"seat-row-4\">\r\n");
      out.write("            <ol class=\"seats\">\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-13\"\r\n");
      out.write("                  value=\"13\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                  disabled\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-13\"> 13 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-14\"\r\n");
      out.write("                  value=\"14\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-14\"> 14 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-15\"\r\n");
      out.write("                  value=\"15\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-15\"> 15 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-16\"\r\n");
      out.write("                  value=\"16\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-16\"> 16 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"seat-row-5\">\r\n");
      out.write("            <ol class=\"seats\">\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-17\"\r\n");
      out.write("                  value=\"17\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-17\"> 17 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-18\"\r\n");
      out.write("                  value=\"18\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-18\"> 18 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-19\"\r\n");
      out.write("                  value=\"19\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-19\"> 19 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-20\"\r\n");
      out.write("                  value=\"20\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-20\"> 20 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"seat-row-6\">\r\n");
      out.write("            <ol class=\"seats\">\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-21\"\r\n");
      out.write("                  value=\"21\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-21\"> 21 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-22\"\r\n");
      out.write("                  value=\"22\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-22\"> 22 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-23\"\r\n");
      out.write("                  value=\"23\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-23\"> 23 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-24\"\r\n");
      out.write("                  value=\"24\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-24\"> 24 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"seat-row-7\">\r\n");
      out.write("            <ol class=\"seats\">\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <label for=\"seat-radio-1-BLANK\" style=\"background: none\"></label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <label for=\"seat-radio-1-BLANK\" style=\"background: none\"></label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-25\"\r\n");
      out.write("                  onclick=\"func()\"\r\n");
      out.write("                  value=\"25\"\r\n");
      out.write("                  required=\"\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-25\"> 25 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-26\"\r\n");
      out.write("                  value=\"26\"\r\n");
      out.write("                  onclick=\"func()\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-26\"> 26 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"seat-row-8\">\r\n");
      out.write("            <ol class=\"seats\">\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <label for=\"seat-radio-1-BLANK\" style=\"background: none\"></label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <label for=\"seat-radio-1-BLANK\" style=\"background: none\"></label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\">\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-27\"\r\n");
      out.write("                  value=\"27\"\r\n");
      out.write("                  onclick=\"func()\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-27\"> 27 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"seat\" >\r\n");
      out.write("                <input\r\n");
      out.write("                  role=\"input-passenger-seat\"\r\n");
      out.write("                  name=\"passengers[1][seat]\"\r\n");
      out.write("                  id=\"seat-radio-1-28\"\r\n");
      out.write("                  value=\"28\"\r\n");
      out.write("                  onclick=\"func()\"\r\n");
      out.write("                  type=\"radio\"\r\n");
      out.write("                  \r\n");
      out.write("                />\r\n");
      out.write("                <label for=\"seat-radio-1-28\"> 28 </label>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div style=\"font-weight: 600;\">Selected seat</div>\r\n");
      out.write("          <li class=\"seat\"  >\r\n");
      out.write("          \r\n");
      out.write("            <!-- <label for=\"seat-radio-1-14\" id=\"result\" name=\"seatNumber\"> 0</label>  -->   \r\n");
      out.write("              <input type=\"text\" id=\"seatt\" name=\"seatNumber\" />\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("          \r\n");
      out.write("         <div id=\"result\" ></div> \r\n");
      out.write("          </li>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#exampleModal\" > <input type =\"submit\"   >\r\n");
      out.write("            \r\n");
      out.write("          </button> \r\n");
      out.write("          \r\n");
      out.write("          <!--  <input type=\"submit\"> -->\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <div class=\"text-left mt-2\">\r\n");
      out.write("          <button\r\n");
      out.write("            class=\"btn btn-primary btn-xs mb-2 btn-style btn-hover1\"\r\n");
      out.write("            style=\"background-color: #3783b5\"\r\n");
      out.write("          >\r\n");
      out.write("            Available\r\n");
      out.write("          </button>\r\n");
      out.write("          <button\r\n");
      out.write("            class=\"btn btn-success btn-xs mb-2 btn-style btn-hover2\"\r\n");
      out.write("            style=\"background-color: #46be8a\"\r\n");
      out.write("          >\r\n");
      out.write("            Choosen\r\n");
      out.write("          </button>\r\n");
      out.write("          <button\r\n");
      out.write("            class=\"btn btn-danger btn-xs mb-2 btn-style btn-hover3\"\r\n");
      out.write("            style=\"background-color: #f73737\"\r\n");
      out.write("          >\r\n");
      out.write("            Booked\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("  const buttons = document.getElementsByName(\"passengers[1][seat]\");\r\n");
      out.write("  const result = document.getElementById(\"result\");\r\n");
      out.write("\r\n");
      out.write("  const buttonPressed = (e) => {\r\n");
      out.write("    result.textContent = e.target.value;\r\n");
      out.write("    var re = result.textContent;\r\n");
      out.write("    document.getElementById(\"seatt\").value = re;\r\n");
      out.write("  };\r\n");
      out.write("\r\n");
      out.write("  for (let button of buttons) {\r\n");
      out.write("    button.addEventListener(\"click\", buttonPressed);\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
