/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-02-14 18:27:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class seatsAvailable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Seleção de lugares</title>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("      *,\r\n");
      out.write("      *:before,\r\n");
      out.write("      *:after {\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      html {\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .plane {\r\n");
      out.write("        margin: 20px auto;\r\n");
      out.write("        max-width: 300px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .exit {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("      }\r\n");
      out.write("      .exit:before,\r\n");
      out.write("      .exit:after {\r\n");
      out.write("        content: \"EXIT\";\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        line-height: 18px;\r\n");
      out.write("        padding: 0px 2px;\r\n");
      out.write("        font-family: \"Arial Narrow\", Arial, sans-serif;\r\n");
      out.write("        display: block;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        background: green;\r\n");
      out.write("        color: white;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("        transform: translate(0, -50%);\r\n");
      out.write("      }\r\n");
      out.write("      .exit:before {\r\n");
      out.write("        left: 0;\r\n");
      out.write("      }\r\n");
      out.write("      .exit:after {\r\n");
      out.write("        right: 0;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .fuselage {\r\n");
      out.write("        border-right: 5px solid #d8d8d8;\r\n");
      out.write("        border-left: 5px solid #d8d8d8;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      ol {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .seats {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        flex-wrap: nowrap;\r\n");
      out.write("        justify-content: flex-start;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .seat {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex: 0 0 14.28571428571429%;\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("      }\r\n");
      out.write("      .seat:nth-child(3) {\r\n");
      out.write("        margin-right: 14.28571428571429%;\r\n");
      out.write("      }\r\n");
      out.write("      .seat input[type=\"checkbox\"] {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        opacity: 0;\r\n");
      out.write("      }\r\n");
      out.write("      .seat input[type=\"checkbox\"]:checked + label {\r\n");
      out.write("        background: #bada55;\r\n");
      out.write("        -webkit-animation-name: rubberBand;\r\n");
      out.write("        animation-name: rubberBand;\r\n");
      out.write("        animation-duration: 300ms;\r\n");
      out.write("        animation-fill-mode: both;\r\n");
      out.write("      }\r\n");
      out.write("      .seat input[type=\"checkbox\"]:disabled + label {\r\n");
      out.write("        background: #dddddd;\r\n");
      out.write("        text-indent: -9999px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("      }\r\n");
      out.write("      .seat input[type=\"checkbox\"]:disabled + label:after {\r\n");
      out.write("        content: \"X\";\r\n");
      out.write("        text-indent: 0;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 4px;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        transform: translate(-50%, 0%);\r\n");
      out.write("      }\r\n");
      out.write("      .seat input[type=\"checkbox\"]:disabled + label:hover {\r\n");
      out.write("        box-shadow: none;\r\n");
      out.write("        cursor: not-allowed;\r\n");
      out.write("      }\r\n");
      out.write("      .seat label {\r\n");
      out.write("        display: block;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        line-height: 1.5rem;\r\n");
      out.write("        padding: 4px 0;\r\n");
      out.write("        background: #f42536;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        animation-duration: 300ms;\r\n");
      out.write("        animation-fill-mode: both;\r\n");
      out.write("      }\r\n");
      out.write("      .seat label:before {\r\n");
      out.write("        content: \"\";\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        width: 75%;\r\n");
      out.write("        height: 75%;\r\n");
      out.write("        top: 1px;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        transform: translate(-50%, 0%);\r\n");
      out.write("        background: rgba(255, 255, 255, 0.4);\r\n");
      out.write("        border-radius: 3px;\r\n");
      out.write("      }\r\n");
      out.write("      .seat label:hover {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        box-shadow: 0 0 0px 2px #5c6aff;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      @-webkit-keyframes rubberBand {\r\n");
      out.write("        0% {\r\n");
      out.write("          -webkit-transform: scale3d(1, 1, 1);\r\n");
      out.write("          transform: scale3d(1, 1, 1);\r\n");
      out.write("        }\r\n");
      out.write("        30% {\r\n");
      out.write("          -webkit-transform: scale3d(1.25, 0.75, 1);\r\n");
      out.write("          transform: scale3d(1.25, 0.75, 1);\r\n");
      out.write("        }\r\n");
      out.write("        40% {\r\n");
      out.write("          -webkit-transform: scale3d(0.75, 1.25, 1);\r\n");
      out.write("          transform: scale3d(0.75, 1.25, 1);\r\n");
      out.write("        }\r\n");
      out.write("        50% {\r\n");
      out.write("          -webkit-transform: scale3d(1.15, 0.85, 1);\r\n");
      out.write("          transform: scale3d(1.15, 0.85, 1);\r\n");
      out.write("        }\r\n");
      out.write("        65% {\r\n");
      out.write("          -webkit-transform: scale3d(0.95, 1.05, 1);\r\n");
      out.write("          transform: scale3d(0.95, 1.05, 1);\r\n");
      out.write("        }\r\n");
      out.write("        75% {\r\n");
      out.write("          -webkit-transform: scale3d(1.05, 0.95, 1);\r\n");
      out.write("          transform: scale3d(1.05, 0.95, 1);\r\n");
      out.write("        }\r\n");
      out.write("        100% {\r\n");
      out.write("          -webkit-transform: scale3d(1, 1, 1);\r\n");
      out.write("          transform: scale3d(1, 1, 1);\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("      @keyframes rubberBand {\r\n");
      out.write("        0% {\r\n");
      out.write("          -webkit-transform: scale3d(1, 1, 1);\r\n");
      out.write("          transform: scale3d(1, 1, 1);\r\n");
      out.write("        }\r\n");
      out.write("        30% {\r\n");
      out.write("          -webkit-transform: scale3d(1.25, 0.75, 1);\r\n");
      out.write("          transform: scale3d(1.25, 0.75, 1);\r\n");
      out.write("        }\r\n");
      out.write("        40% {\r\n");
      out.write("          -webkit-transform: scale3d(0.75, 1.25, 1);\r\n");
      out.write("          transform: scale3d(0.75, 1.25, 1);\r\n");
      out.write("        }\r\n");
      out.write("        50% {\r\n");
      out.write("          -webkit-transform: scale3d(1.15, 0.85, 1);\r\n");
      out.write("          transform: scale3d(1.15, 0.85, 1);\r\n");
      out.write("        }\r\n");
      out.write("        65% {\r\n");
      out.write("          -webkit-transform: scale3d(0.95, 1.05, 1);\r\n");
      out.write("          transform: scale3d(0.95, 1.05, 1);\r\n");
      out.write("        }\r\n");
      out.write("        75% {\r\n");
      out.write("          -webkit-transform: scale3d(1.05, 0.95, 1);\r\n");
      out.write("          transform: scale3d(1.05, 0.95, 1);\r\n");
      out.write("        }\r\n");
      out.write("        100% {\r\n");
      out.write("          -webkit-transform: scale3d(1, 1, 1);\r\n");
      out.write("          transform: scale3d(1, 1, 1);\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("      .rubberBand {\r\n");
      out.write("        -webkit-animation-name: rubberBand;\r\n");
      out.write("        animation-name: rubberBand;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"plane\">\r\n");
      out.write("      <h1>Selecionar lugar</h1>\r\n");
      out.write("      <div class=\"fuselage\"></div>\r\n");
      out.write("      <ol class=\"cabin fuselage\">\r\n");
      out.write("        <li class=\"row row--1\">\r\n");
      out.write("          <ol class=\"seats\" type=\"A\">\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"1A\" />\r\n");
      out.write("              <label for=\"1A\">1A</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"1B\" />\r\n");
      out.write("              <label for=\"1B\">1B</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"1C\" />\r\n");
      out.write("              <label for=\"1C\">1C</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" disabled id=\"1D\" />\r\n");
      out.write("              <label for=\"1D\">Occupied</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"1E\" />\r\n");
      out.write("              <label for=\"1E\">1E</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"1F\" />\r\n");
      out.write("              <label for=\"1F\">1F</label>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"row row--2\">\r\n");
      out.write("          <ol class=\"seats\" type=\"A\">\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"2A\" />\r\n");
      out.write("              <label for=\"2A\">2A</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"2B\" />\r\n");
      out.write("              <label for=\"2B\">2B</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"2C\" />\r\n");
      out.write("              <label for=\"2C\">2C</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"2D\" />\r\n");
      out.write("              <label for=\"2D\">2D</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"2E\" />\r\n");
      out.write("              <label for=\"2E\">2E</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"2F\" />\r\n");
      out.write("              <label for=\"2F\">2F</label>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"row row--3\">\r\n");
      out.write("          <ol class=\"seats\" type=\"A\">\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"3A\" />\r\n");
      out.write("              <label for=\"3A\">3A</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"3B\" />\r\n");
      out.write("              <label for=\"3B\">3B</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"3C\" />\r\n");
      out.write("              <label for=\"3C\">3C</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"3D\" />\r\n");
      out.write("              <label for=\"3D\">3D</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"3E\" />\r\n");
      out.write("              <label for=\"3E\">3E</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"3F\" />\r\n");
      out.write("              <label for=\"3F\">3F</label>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"row row--4\">\r\n");
      out.write("          <ol class=\"seats\" type=\"A\">\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"4A\" />\r\n");
      out.write("              <label for=\"4A\">4A</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"4B\" />\r\n");
      out.write("              <label for=\"4B\">4B</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"4C\" />\r\n");
      out.write("              <label for=\"4C\">4C</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"4D\" />\r\n");
      out.write("              <label for=\"4D\">4D</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"4E\" />\r\n");
      out.write("              <label for=\"4E\">4E</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"4F\" />\r\n");
      out.write("              <label for=\"4F\">4F</label>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"row row--5\">\r\n");
      out.write("          <ol class=\"seats\" type=\"A\">\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"5A\" />\r\n");
      out.write("              <label for=\"5A\">5A</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"5B\" />\r\n");
      out.write("              <label for=\"5B\">5B</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"5C\" />\r\n");
      out.write("              <label for=\"5C\">5C</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"5D\" />\r\n");
      out.write("              <label for=\"5D\">5D</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"5E\" />\r\n");
      out.write("              <label for=\"5E\">5E</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"5F\" />\r\n");
      out.write("              <label for=\"5F\">5F</label>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"row row--6\">\r\n");
      out.write("          <ol class=\"seats\" type=\"A\">\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"6A\" />\r\n");
      out.write("              <label for=\"6A\">6A</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"6B\" />\r\n");
      out.write("              <label for=\"6B\">6B</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"6C\" />\r\n");
      out.write("              <label for=\"6C\">6C</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"6D\" />\r\n");
      out.write("              <label for=\"6D\">6D</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"6E\" />\r\n");
      out.write("              <label for=\"6E\">6E</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"6F\" />\r\n");
      out.write("              <label for=\"6F\">6F</label>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"row row--7\">\r\n");
      out.write("          <ol class=\"seats\" type=\"A\">\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"7A\" />\r\n");
      out.write("              <label for=\"7A\">7A</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"7B\" />\r\n");
      out.write("              <label for=\"7B\">7B</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"7C\" />\r\n");
      out.write("              <label for=\"7C\">7C</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"7D\" />\r\n");
      out.write("              <label for=\"7D\">7D</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"7E\" />\r\n");
      out.write("              <label for=\"7E\">7E</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"7F\" />\r\n");
      out.write("              <label for=\"7F\">7F</label>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"row row--8\">\r\n");
      out.write("          <ol class=\"seats\" type=\"A\">\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"8A\" />\r\n");
      out.write("              <label for=\"8A\">8A</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"8B\" />\r\n");
      out.write("              <label for=\"8B\">8B</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"8C\" />\r\n");
      out.write("              <label for=\"8C\">8C</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"8D\" />\r\n");
      out.write("              <label for=\"8D\">8D</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"8E\" />\r\n");
      out.write("              <label for=\"8E\">8E</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"8F\" />\r\n");
      out.write("              <label for=\"8F\">8F</label>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"row row--9\">\r\n");
      out.write("          <ol class=\"seats\" type=\"A\">\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"9A\" />\r\n");
      out.write("              <label for=\"9A\">9A</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"9B\" />\r\n");
      out.write("              <label for=\"9B\">9B</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"9C\" />\r\n");
      out.write("              <label for=\"9C\">9C</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"9D\" />\r\n");
      out.write("              <label for=\"9D\">9D</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"9E\" />\r\n");
      out.write("              <label for=\"9E\">9E</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"9F\" />\r\n");
      out.write("              <label for=\"9F\">9F</label>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"row row--10\">\r\n");
      out.write("          <ol class=\"seats\" type=\"A\">\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"10A\" />\r\n");
      out.write("              <label for=\"10A\">10A</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"10B\" />\r\n");
      out.write("              <label for=\"10B\">10B</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"10C\" />\r\n");
      out.write("              <label for=\"10C\">10C</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"10D\" />\r\n");
      out.write("              <label for=\"10D\">10D</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"10E\" />\r\n");
      out.write("              <label for=\"10E\">10E</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"seat\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"10F\" />\r\n");
      out.write("              <label for=\"10F\">10F</label>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ol>\r\n");
      out.write("      <div class=\"fuselage\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
